# Replace this URL with your actual ngrok forwarding URL
ollama_base_url = "https://preimaginary-otis-nonvehemently.ngrok-free.dev/"

# GROQ_API_KEY = "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"